import express from 'express';
import * as C from '../controllers/detalle_carrito.controller.js';
const router = express.Router();
router.get('/', C.getAll);
router.get('/:id', C.getById);
router.get('/carrito/:car_id', C.getByCarrito);
router.post('/', C.create);
router.put('/:id', C.update);
router.delete('/:id', C.remove);
export default router;